types = ["story", "horror", "action", "fighting", "rpg", "strategy", "simulation", 
         "puzzle", "sport", "racing", "sandbox", "shooter", "platformer", "space", "card"]



game_data = [["story", "Red Dead Redemption 2", "Mature", "Very Positive", "59.99", ["Steam", "Epic Games"]],
             ["story", "Cyberpunk 2077", "Mature", "Very Positive", "59.99", ["Steam", "Epic Games"]],
             ["story", "It Takes Two", "Teen", "Very Positive", "39.99", ["Steam", "Epic Games"]],
             ["horror", "Devour", "Mature", "Very Positive", "4.99", ["Steam"]],
             ["horror", "Subnautica", "Everyone", "Overwhelmingly Positive", "29.99", ["Steam", "Epic Games"]],
             ["horror", "Amnesia: The Bunker", "Mature", "Very Positive", "24.99", ["Steam", "Epic Games"]],
             ["action", "Halo: The Master Chief Collection", "Mature", "Very Positive", "39.99", ["Steam", "Battle Net"]],
             ["action", "Doom Eternal", "Mature", "Very Positive", "39.99", ["Steam"]],
             ["action", "Hell Divers 2", "Mature", "Mostly Positive", "39.99", ["Steam"]],
             ["fighting", "Street Fighter 6", "Teen", "Very Positive", "59.99", ["Steam"]],
             ["fighting", "Mortal Kombat 1", "Mature", "Mostly Positive", "69.99", ["Steam", "Epic Games"]],
             ["fighting", "Tekken 8", "Teen", "Mostly Positive", "69.99", ["Steam"]],
             ["rpg", "The Elder Scrolls V: Skyrim Special Edition", "Mature", "Very Positive", "39.99", ["Steam"]],
             ["rpg", "Baldur's Gate 3", "Mature", "Overwhelmingly Positive", "59.99", ["Steam"]],
             ["rpg", "Fallout: New Vegas", "Mature", "Overwhelmingly Positive", "9.99", ["Steam", "Epic Games"]],
             ["strategy", "Hearts Of Iron IV", "Everyone", "Very Positive", "49.99", ["Steam"]],
             ["strategy", "Sid Meier's Civilization VI", "Everyone", "Very Positive", "59.99", ["Steam", "Epic Games"]],
             ["strategy", "Stellaris", "Everyone", "Very Positive", "39.99", ["Steam"]],
             ["simulation", "The Sims 4", "Teen", "Very Positive", "Free", ["Steam", "Epic Games"]],
             ["simulation", "Bum Simulator", "Mature", "Very Positive", "17.99", ["Steam"]],
             ["simulation", "Tabletop Simulator", "Everyone", "Overwhelmingly Positive", "19.99", ["Steam"]] ,
             ["puzzle", "Tetris Effect: Connected", "Everyone", "Overwhelmingly Positive", "39.99", ["Steam", "Epic Games"]],
             ["puzzle", "Station to Station", "Everyone", "Very Positive", "17.99", ["Steam"]],
             ["puzzle", "Escape Academy", "Teen", "Very Positive", "19.99", ["Steam", "Epic Games"]],
             ["sport", "Riders Republic", "Teen", "Very Positive", "39.99", ["Steam", "Epic Games"]],
             ["sport", "Pro Soccer Online", "Teen", "Very Positive", "9.99", ["Steam"]],
             ["sport", "Rooftops & Alleys: The Parkour Game", "Teen", "Overwhelmingly Positive", "15.99", ["Steam"]],
             ["racing", "Forza Horizon 5", "Everyone", "Very Positive", "59.99", ["Steam"]],
             ["racing", "GRIP: Combat Racing", "Everyone", "Very Positive", "29.99", ["Steam"]],
             ["racing", "BeamNG.drive", "Everyone", "Overwhelmingly Positive", "24.99", ["Steam"]],
             ["sandbox", "Anno 1800", "Teen", "Very Positive", "59.99", ["Steam", "Epic Games"]],
             ["sandbox", "TABS: Tottaly Accurate Battle Simulator", "Teen", "Overwhelmingly Positive", "19.99", ["Steam"]],
             ["sandbox", "Garry's Mod", "Teen", "Overwhelmingly Positive", "9.99", ["Steam"]],
             ["shooter", "Far Cry 4", "Mature", "Very Positive", "29.99", ["Steam", "Epic Games"]],
             ["shooter", "Counter-Strike 2", "Mature", "Very Positive", "Free", ["Steam"]],
             ["shooter", "Destiny 2", "Teen", "Very Positive", "Free", ["Steam", "Epic Games"]],
             ["platformer", "Nine Sols", "Teen", "Very Positive", "29.99", ["Steam"]],
             ["platformer", "Hollow Knight", "Everyone", "Overwhelmingly Positive", "14.99", ["Steam"]],
             ["platformer", "ANIMAL WELL", "Everyone", "Overwhelmingly Positive", "24.99", ["Steam"]],
             ["space", "X4: Foundations", "Everyone", "Mostly Positive", "49.99", ["Steam"]],
             ["space", "Space Engineers", "Everyone", "Very Positive", "19.99", ["Steam"]],
             ["space", "Spore", "Everyone", "Very Positive", "19.99", ["Steam"]],
             ["card", "Slay the Spire", "Everyone", "Overwhelmingly Positive", "24.99", ["Steam"]],
             ["card", "Inscryption", "Teen", "Overwhelmingly Positive", "19.99", ["Steam"]],
             ["card", "Yu-Gi-Oh! Master Duel", "Teen", "Mostly Positive", "Free", ["Steam"]]]


